name: Python application test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12' 

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        Xvfb :99 -screen 0 1280x1024x24 &
        export DISPLAY=:99
        pytest test_app.py
