name: Python application test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' 

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb  # Устанавливаем xvfb для создания виртуального дисплея
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      uses: GabrielBB/xvfb-action@v1
      with:
        run: pytest
